#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 22 12:55:27 +0000 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim SolveForWSim2_behav -key {Behavioral:sim_1:Functional:SolveForWSim2} -tclbatch SolveForWSim2.tcl -view /home/user/EE2026-Calculator/Untitled/SolveForWSim_behav.wcfg -log simulate.log"
xsim SolveForWSim2_behav -key {Behavioral:sim_1:Functional:SolveForWSim2} -tclbatch SolveForWSim2.tcl -view /home/user/EE2026-Calculator/Untitled/SolveForWSim_behav.wcfg -log simulate.log

